# Set the 'alt' key as the main modifier key (mod).
# Other options: 'cmd', 'ctrl', 'shift'
default-root-container-layout = 'tiles'
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = false
default-root-container-orientation = 'horizontal'
automatically-unhide-macos-hidden-apps = true

[mode.main.binding]
alt-g = 'exec-and-forget aerospace-scratchpad show Ghostty'
alt-v = 'exec-and-forget aerospace-scratchpad show VSCodium'
alt-c = 'exec-and-forget aerospace-scratchpad show ChatGPT'
alt-f = 'exec-and-forget aerospace-scratchpad show Firefox'
alt-d = 'exec-and-forget aerospace-scratchpad show Discord'
alt-s = 'exec-and-forget aerospace-scratchpad show Spotify' 
alt-q = 'exec-and-forget aerospace-scratchpad show Finder'
alt-b = 'exec-and-forget aerospace-scratchpad show Books'

alt-o = 'exec-and-forget aerospace-scratchpad show Obsidian'

alt-z = 'fullscreen'    






