theme = "vercel"
[editor]
clipboard-provider = "pasteboard"
default-yank-register = "+"


[keys.select]
"A-x" = "normal_mode"
"Cmd-x" = "normal_mode"
"esc" = "no_op"

[keys.insert]
"Cmd-x" = "normal_mode"
"A-x" = "normal_mode"
"esc" = "no_op"

